name: deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0,4,8,12,16,20 * * *"

jobs:
  build_data:
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: echo event name
        run: echo event name is ${{ github.event_name }}

      - name: checkout
        uses: actions/checkout@v3

      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: frontend/yarn.lock
      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: fetch and upload data
        if: github.event_name == 'schedule'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn run fetch:languages
          yarn run fetch:data
          yarn run upload:data

  deploy_frontend:
    defaults:
      run:
        working-directory: frontend
    permissions:
      id-token: write
      contents: read
    needs:
      - build_data
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: frontend/yarn.lock
      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: build
        run: yarn run build
      - name: upload to s3
        run: aws s3 sync --delete ./out/ s3://github-stats-frontend
